
id = "Kitchan.TestMod"
name = "Testing"
description = "I am testing."
version = "1.0.0"
homepage = "https://github.com/boonePoulsen/Kitchan.TestMod"
author = "Kitchan"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./WebfishingSampleMod/WebfishingSampleMod.csproj"
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"
